In [7]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
x = torch.randn(10, 3)
x

tensor([[-0.1490,  2.8565, -1.0063],
        [ 2.1377,  0.6082, -0.0938],
        [-0.1372,  0.0705,  1.1073],
        [-0.8942, -0.3152,  0.5590],
        [ 0.6666,  0.0869,  1.6771],
        [ 0.1817, -0.4751, -0.8059],
        [-0.5754, -0.7365, -0.8013],
        [-0.2404,  0.2531, -0.9472],
        [ 0.6184, -0.0474,  0.6692],
        [ 1.2345,  2.0137, -0.0497]])

In [8]:
codebook = nn.Embedding(8, 3)
codebook.weight.data.uniform_(-1 / 8, 1 / 8)

tensor([[-0.0414,  0.0655, -0.1105],
        [-0.0622,  0.0570,  0.0945],
        [ 0.1032,  0.0581, -0.0423],
        [-0.0082, -0.0073, -0.1164],
        [-0.1064, -0.0487, -0.0458],
        [-0.0574,  0.0851, -0.0542],
        [ 0.0746, -0.0873, -0.1223],
        [-0.0933, -0.0970, -0.0898]])

In [9]:
codebook.weight.shape

torch.Size([8, 3])

In [ ]:
x_2 = torch.sum(x**2, dim=1, keepdim=True)
x_2.shape

torch.Size([10, 1])

In [11]:
codebook_2 = torch.sum(codebook.weight**2, dim=1)
codebook_2.shape

torch.Size([8])

In [14]:
distance = x_2 + codebook_2
print(x_2)
print(codebook_2)
print(distance)
distance.shape

tensor([[9.1945],
        [4.9485],
        [1.2499],
        [1.2113],
        [3.2646],
        [0.9081],
        [1.5156],
        [1.0190],
        [0.8325],
        [5.5814]])
tensor([0.0182, 0.0160, 0.0158, 0.0137, 0.0158, 0.0135, 0.0281, 0.0262],
       grad_fn=<SumBackward1>)
tensor([[9.2127, 9.2105, 9.2103, 9.2082, 9.2103, 9.2080, 9.2226, 9.2207],
        [4.9667, 4.9646, 4.9643, 4.9622, 4.9643, 4.9620, 4.9767, 4.9747],
        [1.2681, 1.2660, 1.2657, 1.2636, 1.2657, 1.2634, 1.2781, 1.2761],
        [1.2295, 1.2274, 1.2271, 1.2250, 1.2271, 1.2248, 1.2395, 1.2375],
        [3.2828, 3.2806, 3.2804, 3.2782, 3.2803, 3.2780, 3.2927, 3.2907],
        [0.9263, 0.9242, 0.9239, 0.9218, 0.9239, 0.9216, 0.9363, 0.9343],
        [1.5338, 1.5317, 1.5314, 1.5293, 1.5314, 1.5291, 1.5438, 1.5418],
        [1.0372, 1.0351, 1.0348, 1.0327, 1.0348, 1.0325, 1.0472, 1.0452],
        [0.8507, 0.8485, 0.8483, 0.8461, 0.8483, 0.8459, 0.8606, 0.8586],
        [5.5997, 5.5975, 5.5973, 5.5951, 5.5972, 

torch.Size([10, 8])

In [15]:
dot = torch.matmul(x, codebook.weight.t())
dot.shape

torch.Size([10, 8])

In [17]:
indices = torch.argmin(distance, dim=1)
print(indices)
indices.shape

tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])


torch.Size([10])

RuntimeError: operator torchvision::nms does not exist